# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code_execution.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "codepanda.SourceCodeRequest" do
    optional :code, :string, 1
  end
  add_message "codepanda.ExecutedResult" do
    optional :result, :string, 1
    optional :success, :bool, 2
  end
end

module Codepanda
  SourceCodeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("codepanda.SourceCodeRequest").msgclass
  ExecutedResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("codepanda.ExecutedResult").msgclass
end
