# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: code_execution.proto for package 'codepanda'

require "grpc"
require_relative "code_execution_pb"

module Codepanda
  module CodeExecution
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "codepanda.CodeExecution"

      # Sends a greeting
      rpc :Execute, SourceCodeRequest, ExecutedResult
    end

    Stub = Service.rpc_stub_class
  end
end
